version: "4"
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: brainphil
      MONGO_INITDB_ROOT_PASSWORD: 9J7DUMZJl5bxPCHU
      MONGO_INITDB_ROOT_DATABASE: db1
    volumes:
      - ./data:/data/db